dist: trusty
language: python
python:
  - 3.5
cache: pip
addons:
  postgresql: 9.5

env:
  - DJANGO=1.11 TESTENV=travis-postgresql DATABASE=ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:USER=postgres:PASSWORD=squad:HOST=127.0.0.1:PORT=5432
  - DJANGO=1.11 TESTENV=travis-sqlite3 DATABASE=

install:
  - pip install --upgrade setuptools
  - pip install nose
  - pip install .
  - pip freeze

script:
  - nosetests

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#linaro-qa"
